spring:
  application:
    name: notification-service

  rabbitmq:
    template:
      default-receive-queue: notification-queue
      payment-queue: payment-queue
      
feign:
  hystrix:
    enabled: true

server:
  port: 8081